/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sap_sapphire_swlib_SWLib */

#ifndef _Included_com_sap_sapphire_swlib_SWLib
#define _Included_com_sap_sapphire_swlib_SWLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sap_sapphiredemo_service_NativeHelp
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sap_sapphiredemo_service_NativeHelp_init
(JNIEnv *, jclass);

/*
 * Class:     com_sap_sapphiredemo_service_NativeHelp
 * Method:    uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sap_sapphiredemo_service_NativeHelp_uninit
(JNIEnv *, jclass);

/*
 * Class:     com_sap_sapphiredemo_service_NativeHelp
 * Method:    postJson
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sap_sapphiredemo_service_NativeHelp_postJson
(JNIEnv *, jclass, jstring, jstring);


/*
 * Class:     com_sap_sapphiredemo_service_NativeHelp
 * Method:    getCurTimestamp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sap_sapphiredemo_service_NativeHelp_getCurTimestamp
        (JNIEnv *, jclass);


/*
 * Class:     com_sap_sapphiredemo_service_NativeHelp
 * Method:    openLocationFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_sap_sapphiredemo_service_NativeHelp_openLocationFile
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sap_sapphiredemo_service_NativeHelp
 * Method:    writeLocation
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_com_sap_sapphiredemo_service_NativeHelp_writeLocation
(JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     com_sap_sapphiredemo_service_NativeHelp
 * Method:    closeLocationFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sap_sapphiredemo_service_NativeHelp_closeLocationFile
(JNIEnv *, jclass, jlong);


#ifdef __cplusplus
}
#endif
#endif
